-- MySQL Script generated by MySQL Workbench
-- Sat Jul  4 22:58:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cancha` ;

CREATE TABLE IF NOT EXISTS `cancha` (
  `idcancha` INT NOT NULL AUTO_INCREMENT,
  `tipo_cancha` VARCHAR(50) NULL DEFAULT NULL,
  `precio_hora` DECIMAL(10,0) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcancha`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

CREATE TABLE IF NOT EXISTS `clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `rol` ENUM('Administrador', 'Recepcionista', 'Duenio') NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL,
  `estado` ENUM('Activo', 'Inactivo') NULL DEFAULT 'Activo',
  `modificado_por` INT NULL,
  `fecha_modificacion` DATETIME NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservas` ;

CREATE TABLE IF NOT EXISTS `reservas` (
  `idreservas` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` DATETIME NULL DEFAULT NULL,
  `hora_fin` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('Reservado', 'Confirmado', 'Cancelado', 'Pagado', 'Pendiente', 'Finalizado') NOT NULL DEFAULT 'Pendiente',
  `usuario_idusuario` INT NOT NULL,
  `cancha_idcancha` INT NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idreservas`),
  INDEX `fk_reservas_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_reservas_cancha1_idx` (`cancha_idcancha` ASC) VISIBLE,
  INDEX `fk_reservas_clientes1_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_cancha1`
    FOREIGN KEY (`cancha_idcancha`)
    REFERENCES `cancha` (`idcancha`),
  CONSTRAINT `fk_reservas_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `clientes` (`idclientes`),
  CONSTRAINT `fk_reservas_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `usuario` (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagos` ;

CREATE TABLE IF NOT EXISTS `pagos` (
  `idpagos` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `metodo_pago` ENUM('efectivo', 'tarjeta', 'transferencia') NOT NULL,
  `fecha_pago` TIMESTAMP NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  `reservas_idreservas` INT NOT NULL,
  PRIMARY KEY (`idpagos`),
  INDEX `fk_pagos_reservas1_idx` (`reservas_idreservas` ASC),
  CONSTRAINT `fk_pagos_reservas1`
    FOREIGN KEY (`reservas_idreservas`)
    REFERENCES `reservas` (`idreservas`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `recuperacion_de_clave_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recuperacion_de_clave_usuario` ;

CREATE TABLE IF NOT EXISTS `recuperacion_de_clave_usuario` (
  `idrecuperacion_de_clave` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(100) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `expiracion` DATETIME NOT NULL,
  `fecha_de_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idrecuperacion_de_clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recuperacion_de_clave_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recuperacion_de_clave_clientes` ;

CREATE TABLE IF NOT EXISTS `recuperacion_de_clave_clientes` (
  `idrecuperacion_de_clave_clientes` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `fecha_de_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`idrecuperacion_de_clave_clientes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

